### ISSUE TITLE
Coleta Inicial dos Dados e Criação do Dicionário

### ISSUE THREAD

**Issue by davidcomd** [atlantico-academy/equipe2-2024.1#2]
> Fazer a coleta dos dados e criação do dicionário:
> 
> * [ ]  **Coleta inicial de dados**: a equipe deve apresentar um conjunto de dados "cru", no repositório do projeto, salvo na pasta data/raw/.
> * [ ] **Criação do dicionário de dados**: a equipe deve criar um arquivo (ou vários) de dicionário de dados, contendo informações referentes aos conjuntos de dados utilizados no projeto. Serão arquivos no formato CSV, que devem ser guardados na pasta data/external/;

**Comment by pauloricms12** [comment]
LGTM
