### ISSUE TITLE
Exploração Inicial dos Dados 

### ISSUE THREAD

**Issue by davidcomd** [atlantico-academy/equipe2-2024.1#3]
> * Criar um notebook de análise exploratória notebooks/01-exploratory_data_analysis.ipynb, contendo as seguintes seções de texto:
> * [ ]  Descrição dos dados,
> * [ ]  Perguntas de partida e hipóteses,
> * [ ]  Insights, de acordo com o conteúdo visto em aula;

**Comment by pauloricms12** [comment]
LGTM
